# Generated by Django 5.2.3 on 2026-04-14 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_ref', models.CharField(help_text='Unique reference code for the unit (e.g., LV-01)', max_length=50, unique=True)),
                ('property_type', models.CharField(choices=[('LX_VILLA', 'LX Villa'), ('STANDARD_VILLA', 'Standard Villa'), ('APARTMENT', 'Apartment'), ('FLAT', 'Flat')], default='APARTMENT', max_length=20)),
                ('area', models.CharField(help_text='Location or area of the property', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied')], default='VACANT', max_length=15)),
                ('bedrooms', models.PositiveIntegerField(blank=True, help_text='Number of bedrooms', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OCCUPIED', 'Occupied'), ('VACANT', 'Vacant'), ('UNDER_RENOVATION', 'Under Renovation')], default='VACANT', max_length=20)),
                ('vacancy_start_date', models.DateField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='core.property')),
            ],
            options={
                'verbose_name_plural': 'Occupancy Records',
            },
        ),
        migrations.CreateModel(
            name='RentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_annual_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('market_annual_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_review_date', models.DateField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_data', to='core.property')),
            ],
            options={
                'verbose_name_plural': 'Rent Data',
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('annual_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=15)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='core.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='core.tenant')),
            ],
        ),
    ]
