# Generated by Django 5.2.3 on 2026-04-17 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Portfolio Owner', max_length=50)),
                ('access_level', models.CharField(default='Admin', max_length=50)),
                ('portfolio_units', models.IntegerField(default=0)),
                ('location', models.CharField(default='Dubai, UAE', max_length=100)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('timezone', models.CharField(default='GST (UTC+4)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
