# Generated by Django 5.2.3 on 2026-04-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ownerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Mid-Range', 'Mid-Range'), ('Affordable', 'Affordable')], default='Mid-Range', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='facilities',
            field=models.CharField(blank=True, help_text='Comma-separated facilities', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the property (e.g., Palm Luxury Villa 01)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='access_level',
            field=models.CharField(default='Full Owner Access', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, help_text='Location or area of the property', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
    ]
