# Generated by Django 5.2.3 on 2026-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property_area_sqft_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='last_login_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='mfa_methods',
            field=models.CharField(blank=True, default='Authenticator App, SMS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='platform_access',
            field=models.CharField(blank=True, default='Full Owner Access', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='status',
            field=models.CharField(default='Active Session', max_length=50),
        ),
    ]
