# Generated by Django 5.2.3 on 2026-04-21 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ownerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['unit_ref'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='last_login_display',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='mfa_enabled',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='mfa_methods',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='platform_access',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='property',
            name='area_sqft',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='lease',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='lease',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lease',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='payment_frequency',
            field=models.CharField(default='Monthly', max_length=50),
        ),
        migrations.AddField(
            model_name='lease',
            name='vacate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='target_occupancy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='vacancy_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rentdata',
            name='DLD_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentdata',
            name='current_monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rentdata',
            name='market_monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rentdata',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_passport',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nationality',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='lease',
            name='annual_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lease',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Terminated', 'Terminated'), ('Notice', 'Notice')], default='Active', max_length=15),
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant'), ('Under Renovation', 'Under Renovation'), ('Reserved', 'Reserved')], default='Vacant', max_length=30),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='full_name',
            field=models.CharField(default='H. Siddiqui', max_length=255),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='portfolio_units',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Luxury Villas', 'Luxury Villas'), ('Standard Villas', 'Standard Villas'), ('Larger Apartments', 'Larger Apartments'), ('Standard Flats', 'Standard Flats')], editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('LX_VILLA', 'LX Villa'), ('ST_VILLA', 'Standard Villa'), ('APARTMENT', '2-3BR Apartment'), ('FLAT', 'Studio/1BR Flat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_ref',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rentdata',
            name='current_annual_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rentdata',
            name='last_review_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rentdata',
            name='market_annual_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valuation_date', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='core.property')),
            ],
        ),
    ]
