# Generated by Django 5.2.3 on 2026-04-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Analyst', 'Analyst'), ('Manager', 'Manager'), ('Viewer', 'Viewer')], default='Admin', max_length=20),
        ),
    ]
